```{r}
library(gapminder)
library(tidyverse)
```


## Data Manipulation
```{r}
gapminderDf = gapminder

cb_palette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

##load data

lifeExpectancyDf  = read.csv('life_expectancy_years.csv')
gdpPerCapitaDf = read.csv('income_per_person_gdppercapita_ppp_inflation_adjusted.csv' )
populationTotalDf = read.csv("population_total.csv")



## getinng continent mapping from gapminder df


countryContinentMapping = gapminderDf %>% 
  select(country,continent) %>% 
  distinct(country,continent,.keep_all = TRUE)


expectancy_gdp = lifeExpectancyDf %>% 
  inner_join(gdpPerCapitaDf,by = c("country" = "country"),suffix =  c("_exp", "_gdp"))




##joining continent information
expectancy_gdp_cont = expectancy_gdp %>% 
  inner_join(countryContinentMapping,by = c("country" = "country"))



expectancy_gdp_cont = expectancy_gdp_cont %>% 
  select(country,continent,everything())



Exp_GDP_Cont_2018 = expectancy_gdp_cont %>% 
  select(country,continent,X2018_exp,X2018_gdp)


```



## Plot q1

```{r}
ggplot(Exp_GDP_Cont_2018, aes(x = X2018_gdp, y = X2018_exp,color = continent))+ 
  
  geom_point(alpha = 0.3)+scale_color_manual(values = cb_palette)+
  geom_smooth(method = "lm", se = FALSE)+ facet_grid(rows = "continent")+
  theme(legend.position = "none")



```


## Question 2
Data Manipulation

```{r}

expectancyLong = lifeExpectancyDf %>% 
  gather(key = "Year",value = "Expectancy",'X1800':"X2018") %>% 
  mutate(Year = str_replace(Year,'X','')) %>% 
  mutate(Year = as.integer(Year)) %>% inner_join(countryContinentMapping,by = c("country" = "country")) %>% 
  select(country,continent,everything())


populationTotalLong = populationTotalDf %>% 
  gather(key = "Year",value = "Population",'X1800':"X2100") %>% 
  mutate(Year = str_replace(Year,'X','')) %>% 
  mutate(Year = as.integer(Year)) %>% inner_join(countryContinentMapping,by = c("country" = "country")) %>% 
  select(country,continent,everything())


consolidatedExpec = expectancyLong %>% inner_join(populationTotalLong)


avgLifeExp_Long_postWW = consolidatedExpec %>% select(-country) %>%
                group_by(continent,Year) %>% mutate(weightedAvg =   weighted.mean(Expectancy,Population)) %>% 
  distinct(continent,Year,weightedAvg) %>% 
  filter(Year>=1945) %>% rename(Expectancy = weightedAvg)



```


## Plot 


```{r}



ggplot(avgLifeExp_Long_postWW,aes(x = Year,y = Expectancy,color = continent))+geom_point(alpha = 0.3)+scale_color_manual(values = cb_palette)+
  geom_smooth(method = "lm", se = FALSE)+ facet_grid(rows = vars(continent))+
  theme(legend.position = "none")

```





### Question 3

```{r}
expectancyLong = lifeExpectancyDf %>% 
  gather(key = "Year",value = "Expectancy",'X1800':"X2018") %>% 
  mutate(Year = str_replace(Year,'X','')) %>% 
  mutate(Year = as.integer(Year)) %>% inner_join(countryContinentMapping,by = c("country" = "country")) %>% 
  select(country,continent,everything())
  
gdpLong = gdpPerCapitaDf %>% 
  gather(key = "Year",value = "GDP/Capita",'X1800':"X2018") %>% 
  mutate(Year = str_replace(Year,'X','')) %>% 
  mutate(Year = as.integer(Year)) %>% inner_join(countryContinentMapping,by = c("country" = "country")) %>% 
  select(country,continent,everything())


consolidatedDf = expectancyLong %>% 
              inner_join(gdpLong) %>% filter("Year">1945,"GDP/Capita" > 0) %>% 
              mutate(YearBins = cut(Year,6,dig.lab = 4))

consolidatedDf = consolidatedDf %>% select(-Year) %>%    group_by(country,continent,YearBins) %>% summarise_all(mean)



consolidatedDf = consolidatedDf %>% drop_na()

```

### Plot
```{r}
ggplot(consolidatedDf,aes(y = Expectancy,x = `GDP/Capita`,color = continent))+
  scale_color_manual(values = cb_palette)+
  geom_smooth(method = "lm", se = FALSE)+facet_grid(rows = "YearBins")



```